language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  - bash ./prepare_build.sh

install:
  - bash ./build.sh

script:
  - bash ./test.sh 

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
