language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  - bash ./artbio.ubuntu-vm/prepare_build.sh

install:
  - bash ./artbio.ubuntu-vm/build.sh

script:
  - bash ./artbio.ubuntu-vm/test.sh 

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
